"""
SR0628_C: 为 LMM（线性混合模型）生成按距离排列的合并残差 Q-Q 图（PDF + PNG），
并确认 lenient q1plus 数据集的眼睛总数为 71。

说明：
- 复用 SR_LMM_revised.py 中的 LMM 拟合逻辑。
- 每个距离独立拟合 LMM（Subject_ID 为随机效应，Eye 为固定效应），
  收集标准化残差后绘制 Q-Q 图。
- 输出带 SR0628_C 前缀的 PDF/PNG 与 Markdown 报告。
"""
import os
import sys
import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
# 让 PDF 中的文字以可编辑字体（Type 42 TrueType）嵌入，而非默认的 Type 3 轮廓字体
plt.rcParams['pdf.fonttype'] = 42
import scipy.stats as stats

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from SR_LMM_revised import (
    BASE_DIR, FEATURE_ALL, TARGET_COL,
    prepare_lmm_data, fit_lmm_per_distance
)

warnings.filterwarnings('ignore')

OUT_REPORT_DIR = os.path.join(BASE_DIR, 'report')
OUT_FIG_DIR = os.path.join(OUT_REPORT_DIR, 'FIG', 'SR0628_C')
os.makedirs(OUT_FIG_DIR, exist_ok=True)

DATA_GROUP = 'lenient'
MIN_QUADRANTS = 1
OUT_PREFIX = f'SR0628_C_{DATA_GROUP}_q{MIN_QUADRANTS}_LMM_Residual_QQPlots'


def plot_combined_qq(qq_data, n_eyes_total, n_subjects_total, out_path_pdf, out_path_png=None):
    """绘制按距离合并的 LMM 残差 Q-Q 图，同时输出 PDF 与 PNG。"""
    n_dist = len(qq_data)
    if n_dist == 0:
        raise ValueError("No Q-Q data to plot.")

    ncols = 4
    nrows = int(np.ceil(n_dist / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(14, 3.5 * nrows))
    axes = np.atleast_1d(axes).flatten()

    for idx, dist in enumerate(sorted(qq_data.keys())):
        ax = axes[idx]
        residuals = qq_data[dist]['residuals']
        stats.probplot(residuals, dist="norm", plot=ax)
        ax.set_title(f'{dist:.1f} mm')
        ax.grid(True, alpha=0.3)

    # 隐藏多余子图
    for idx in range(n_dist, len(axes)):
        axes[idx].axis('off')

    fig.suptitle(f'Q-Q Plots of LMM Residuals by Distance (n={n_eyes_total} eyes / {n_subjects_total} subjects, {DATA_GROUP} q≥{MIN_QUADRANTS})',
                 fontsize=14, fontweight='bold')
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])

    plt.savefig(out_path_pdf, format='pdf', bbox_inches='tight')
    print(f"  -> Combined Q-Q PDF: {out_path_pdf}")

    if out_path_png:
        plt.savefig(out_path_png, format='png', dpi=300, bbox_inches='tight')
        print(f"  -> Combined Q-Q PNG: {out_path_png}")

    plt.close()


def main():
    print("--- Preparing LMM data (lenient, q1plus) ---")
    df_all = prepare_lmm_data(DATA_GROUP, min_quadrants=MIN_QUADRANTS)

    # 眼睛总数 = Subject_ID（受试者）+ Eye（OD/OS）唯一组合数
    n_eyes_total = df_all[['Subject_ID', 'Eye']].drop_duplicates().shape[0]
    n_subjects_total = df_all['Subject_ID'].nunique()
    print(f"Total unique eyes: {n_eyes_total}")
    print(f"Total unique subjects: {n_subjects_total}")
    assert n_eyes_total == 71, f"Expected 71 eyes, got {n_eyes_total}"

    print("\n--- Fitting LMM per distance ---")
    df_lmm, qq_data = fit_lmm_per_distance(df_all)

    pdf_path = os.path.join(OUT_FIG_DIR, f'{OUT_PREFIX}.pdf')
    png_path = os.path.join(OUT_FIG_DIR, f'{OUT_PREFIX}.png')
    plot_combined_qq(qq_data, n_eyes_total, n_subjects_total, pdf_path, png_path)

    # 生成 Markdown 报告
    md = []
    md.append(f"# SR0628_C LMM 残差 Q-Q 图（按距离合并）\n\n")
    md.append(f"- **数据集**：{DATA_GROUP}，≥{MIN_QUADRANTS} 象限可用\n")
    md.append(f"- **总眼睛数**：{n_eyes_total}（已确认 = 71）\n")
    md.append(f"- **总受试者数**：{n_subjects_total}\n")
    md.append(f"- **模型**：每个距离独立拟合 LMM，Subject 为随机效应，Eye 为固定效应\n")
    md.append(f"- **残差**：标准化后的 LMM 残差\n\n")

    md.append("## 各距离样本量\n\n")
    md.append("| Distance (mm) | Eyes (n) | Subjects (n) |\n")
    md.append("|---------------|----------|---------------|\n")
    for _, row in df_lmm.sort_values('Distance').iterrows():
        md.append(f"| {row['Distance']:.1f} | {int(row['N_eyes'])} | {int(row['N_subjects'])} |\n")
    md.append("\n")

    rel_png = os.path.relpath(png_path, OUT_REPORT_DIR).replace('\\', '/')
    rel_pdf = os.path.relpath(pdf_path, OUT_REPORT_DIR).replace('\\', '/')
    md.append("## 合并 Q-Q 图\n\n")
    md.append(f"![Combined LMM Residual Q-Q]({rel_png})\n\n")
    md.append(f"[Download PDF version]({rel_pdf})\n\n")

    md.append("---\n\n")
    md.append("*Generated by src/SR0628_C_LMM_Residual_QQ_Combined.py*\n")

    md_path = os.path.join(OUT_REPORT_DIR, f'SR0628_C_LMM_Residual_QQ_Combined_{DATA_GROUP}_q{MIN_QUADRANTS}.md')
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(''.join(md))
    print(f"\nSaved report: {md_path}")


if __name__ == '__main__':
    main()
